export type Video = {
  id: string;
  title: string;
  channel: string;
  views: number;
  published: string;
  duration: string;
  thumbnail: string;
  avatar: string;
  alt: string;
  url: string;
  featured?: boolean;
};

const entries = [
  {
    id: "fx01AURORA1",
    title: "I Replaced Every App With One AI Workspace",
    channel: "Circuit Field",
    views: 1_842_319,
    published: "May 18, 2026",
    duration: "12:48",
    thumbnail: "thumbnails/thumb-01.svg",
    avatar: "avatars/avatar-01.svg",
    alt: "A glowing AI orb connecting a laptop, phone, and tablet on a deep blue background",
  },
  {
    id: "fx02TINYMAC2",
    title: "The Tiny Computer That Quietly Won",
    channel: "Object Mode",
    views: 726_084,
    published: "April 2, 2026",
    duration: "9:16",
    thumbnail: "thumbnails/thumb-02.svg",
    avatar: "avatars/avatar-02.svg",
    alt: "A miniature silver desktop computer floating over a bright orange surface",
  },
  {
    id: "fx03ROBOT03",
    title: "Humanoid Robots Are Finally Useful",
    channel: "Tomorrow, Tested",
    views: 3_406_771,
    published: "June 11, 2026",
    duration: "16:22",
    thumbnail: "thumbnails/thumb-03.svg",
    avatar: "avatars/avatar-03.svg",
    alt: "A friendly white humanoid robot standing in a moody industrial workshop",
  },
  {
    id: "fx04NOTES004",
    title: "Your Notes App Is Making You Forget",
    channel: "Human Layer",
    views: 458_201,
    published: "March 27, 2026",
    duration: "8:37",
    thumbnail: "thumbnails/thumb-04.svg",
    avatar: "avatars/avatar-04.svg",
    alt: "A tangled diagram of colorful notes collapsing into a simple white card",
  },
  {
    id: "fx05PHONE05",
    title: "This Phone Has No Apps. That's the Point.",
    channel: "Soft Hardware",
    views: 2_118_640,
    published: "May 5, 2026",
    duration: "11:03",
    thumbnail: "thumbnails/thumb-05.svg",
    avatar: "avatars/avatar-05.svg",
    alt: "A minimal black phone with one luminous command bar on a pale green backdrop",
  },
  {
    id: "fx06BATTRY06",
    title: "The Battery Breakthrough Nobody Explained",
    channel: "Voltage House",
    views: 891_755,
    published: "February 19, 2026",
    duration: "13:41",
    thumbnail: "thumbnails/thumb-06.svg",
    avatar: "avatars/avatar-06.svg",
    alt: "A cutaway battery cell glowing red against a dark technical grid",
  },
  {
    id: "fx07GLASS007",
    title: "I Wore the Future for 30 Days",
    channel: "Near Future Club",
    views: 5_732_910,
    published: "June 24, 2026",
    duration: "21:08",
    thumbnail: "thumbnails/thumb-07.svg",
    avatar: "avatars/avatar-07.svg",
    alt: "A person in profile wearing translucent smart glasses with vivid cyan reflections",
    featured: true,
  },
  {
    id: "fx08SEARCH08",
    title: "Search Is About to Disappear",
    channel: "Signal Office",
    views: 1_204_882,
    published: "April 16, 2026",
    duration: "10:54",
    thumbnail: "thumbnails/thumb-08.svg",
    avatar: "avatars/avatar-08.svg",
    alt: "A search box dissolving into hundreds of colored particles on black",
  },
  {
    id: "fx09CAMERA9",
    title: "Why This Camera Looks Wrong—and Feels Right",
    channel: "Frame State",
    views: 642_097,
    published: "January 30, 2026",
    duration: "14:29",
    thumbnail: "thumbnails/thumb-09.svg",
    avatar: "avatars/avatar-09.svg",
    alt: "An unusual modular camera shown in dramatic red side lighting",
  },
  {
    id: "fx10CHIP010",
    title: "A Computer Designed Like a City",
    channel: "Core Atlas",
    views: 336_912,
    published: "March 4, 2026",
    duration: "17:10",
    thumbnail: "thumbnails/thumb-10.svg",
    avatar: "avatars/avatar-10.svg",
    alt: "A processor rendered as a glowing miniature city viewed from above",
  },
  {
    id: "fx11DESK011",
    title: "The Zero-Distraction Desk Setup",
    channel: "Quiet Systems",
    views: 1_013_447,
    published: "May 29, 2026",
    duration: "7:58",
    thumbnail: "thumbnails/thumb-11.svg",
    avatar: "avatars/avatar-11.svg",
    alt: "A serene white desk with one monitor and a warm circular lamp",
  },
  {
    id: "fx12VOICE12",
    title: "Voice Interfaces Finally Stopped Being Awkward",
    channel: "Input Theory",
    views: 579_331,
    published: "June 3, 2026",
    duration: "11:44",
    thumbnail: "thumbnails/thumb-12.svg",
    avatar: "avatars/avatar-12.svg",
    alt: "A colorful audio waveform flowing between a person and a small device",
  },
  {
    id: "fx13CODE013",
    title: "I Let Agents Build a Product Overnight",
    channel: "Build Relay",
    views: 2_684_005,
    published: "April 25, 2026",
    duration: "18:36",
    thumbnail: "thumbnails/thumb-13.svg",
    avatar: "avatars/avatar-13.svg",
    alt: "Five luminous agent cards assembling a product interface in the dark",
  },
  {
    id: "fx14SCREEN14",
    title: "Screens Are Becoming Liquid",
    channel: "Material Signal",
    views: 819_624,
    published: "February 7, 2026",
    duration: "9:52",
    thumbnail: "thumbnails/thumb-14.svg",
    avatar: "avatars/avatar-14.svg",
    alt: "A flexible display folding like blue fabric over a reflective platform",
  },
  {
    id: "fx15OPEN015",
    title: "The Open Source Hardware Renaissance",
    channel: "Public Circuit",
    views: 274_598,
    published: "May 13, 2026",
    duration: "15:07",
    thumbnail: "thumbnails/thumb-15.svg",
    avatar: "avatars/avatar-15.svg",
    alt: "Colorful modular circuit boards arranged like a construction kit",
  },
  {
    id: "fx16KEYS016",
    title: "I Built the Last Keyboard I'll Ever Need",
    channel: "Tactile Lab",
    views: 947_113,
    published: "March 12, 2026",
    duration: "12:15",
    thumbnail: "thumbnails/thumb-16.svg",
    avatar: "avatars/avatar-16.svg",
    alt: "A sculptural split keyboard with glowing amber keys viewed close up",
  },
  {
    id: "fx17DATAC17",
    title: "Inside the Data Center Under the Ocean",
    channel: "Deep Infrastructure",
    views: 4_128_033,
    published: "January 18, 2026",
    duration: "19:43",
    thumbnail: "thumbnails/thumb-17.svg",
    avatar: "avatars/avatar-17.svg",
    alt: "A submerged glowing data center capsule surrounded by dark blue water",
  },
  {
    id: "fx18HOME018",
    title: "The Smart Home Is Starting Over",
    channel: "Domestic Futures",
    views: 611_890,
    published: "June 8, 2026",
    duration: "10:28",
    thumbnail: "thumbnails/thumb-18.svg",
    avatar: "avatars/avatar-18.svg",
    alt: "A modern home cross section with a single glowing intelligence at its center",
  },
  {
    id: "fx19MAP019",
    title: "Maps for a World That Changes Every Hour",
    channel: "Circuit Field",
    views: 388_470,
    published: "April 8, 2026",
    duration: "8:59",
    thumbnail: "thumbnails/thumb-19.svg",
    avatar: "avatars/avatar-01.svg",
    alt: "A vivid three-dimensional city map updating in concentric waves",
  },
  {
    id: "fx20SOLAR20",
    title: "Solar Got So Cheap It Changed the Math",
    channel: "Voltage House",
    views: 1_559_202,
    published: "March 22, 2026",
    duration: "13:02",
    thumbnail: "thumbnails/thumb-20.svg",
    avatar: "avatars/avatar-06.svg",
    alt: "A field of dark solar panels under an oversized golden sun",
  },
  {
    id: "fx21MOUSE21",
    title: "The Mouse Was Never the Best Idea",
    channel: "Input Theory",
    views: 740_661,
    published: "February 25, 2026",
    duration: "9:31",
    thumbnail: "thumbnails/thumb-21.svg",
    avatar: "avatars/avatar-12.svg",
    alt: "A computer mouse crossed out beside a hand controlling spatial windows",
  },
  {
    id: "fx22HEAT022",
    title: "The Strange Race to Cool AI",
    channel: "Core Atlas",
    views: 982_114,
    published: "May 1, 2026",
    duration: "14:48",
    thumbnail: "thumbnails/thumb-22.svg",
    avatar: "avatars/avatar-10.svg",
    alt: "A red-hot AI processor submerged in a bright blue cooling liquid",
  },
  {
    id: "fx23PRIVACY",
    title: "Privacy Tech Is Having a Comeback",
    channel: "Human Layer",
    views: 201_889,
    published: "January 9, 2026",
    duration: "11:21",
    thumbnail: "thumbnails/thumb-23.svg",
    avatar: "avatars/avatar-04.svg",
    alt: "A translucent glass lock enclosing a luminous personal data sphere",
  },
  {
    id: "fx24FOLD024",
    title: "This Laptop Folds Into Three Devices",
    channel: "Soft Hardware",
    views: 2_937_446,
    published: "June 19, 2026",
    duration: "13:33",
    thumbnail: "thumbnails/thumb-24.svg",
    avatar: "avatars/avatar-05.svg",
    alt: "A bright folding laptop shown in three configurations against vivid purple",
  },
  {
    id: "fx25CITY025",
    title: "The City Being Built for Autonomous Everything",
    channel: "Tomorrow, Tested",
    views: 6_401_775,
    published: "May 22, 2026",
    duration: "24:17",
    thumbnail: "thumbnails/thumb-25.svg",
    avatar: "avatars/avatar-03.svg",
    alt: "A cinematic future city at dusk with autonomous vehicles tracing light paths",
    featured: true,
  },
  {
    id: "fx26LIGHT26",
    title: "A Display Made Entirely of Light",
    channel: "Material Signal",
    views: 530_700,
    published: "April 30, 2026",
    duration: "8:46",
    thumbnail: "thumbnails/thumb-26.svg",
    avatar: "avatars/avatar-14.svg",
    alt: "A hand reaching through a floating holographic display made of light beams",
  },
  {
    id: "fx27SOUND27",
    title: "The Headphones That Map Your Room",
    channel: "Object Mode",
    views: 867_934,
    published: "March 15, 2026",
    duration: "10:12",
    thumbnail: "thumbnails/thumb-27.svg",
    avatar: "avatars/avatar-02.svg",
    alt: "Black headphones surrounded by a colorful three-dimensional room scan",
  },
  {
    id: "fx28MEMORY8",
    title: "Can a Computer Remember Like You Do?",
    channel: "Signal Office",
    views: 1_330_516,
    published: "June 14, 2026",
    duration: "16:39",
    thumbnail: "thumbnails/thumb-28.svg",
    avatar: "avatars/avatar-08.svg",
    alt: "A human silhouette and a computer linked by branching memory fragments",
  },
  {
    id: "fx29SPACE29",
    title: "The New Internet Is Being Built in Orbit",
    channel: "Deep Infrastructure",
    views: 3_772_081,
    published: "February 14, 2026",
    duration: "18:05",
    thumbnail: "thumbnails/thumb-29.svg",
    avatar: "avatars/avatar-17.svg",
    alt: "A network of small satellites forming a luminous mesh around Earth",
  },
  {
    id: "fx30WATCH30",
    title: "Your Watch Knows More Than Your Doctor",
    channel: "Near Future Club",
    views: 2_201_334,
    published: "April 11, 2026",
    duration: "12:56",
    thumbnail: "thumbnails/thumb-30.svg",
    avatar: "avatars/avatar-07.svg",
    alt: "A smartwatch projecting layered health signals around a wrist",
  },
  {
    id: "fx31CAM031",
    title: "Why Every Camera Is Becoming Computational",
    channel: "Frame State",
    views: 491_827,
    published: "May 9, 2026",
    duration: "15:18",
    thumbnail: "thumbnails/thumb-31.svg",
    avatar: "avatars/avatar-09.svg",
    alt: "A camera lens splitting one scene into many computational layers",
  },
  {
    id: "fx32PRINT32",
    title: "We Printed a Working Machine in One Piece",
    channel: "Public Circuit",
    views: 1_091_640,
    published: "March 8, 2026",
    duration: "13:27",
    thumbnail: "thumbnails/thumb-32.svg",
    avatar: "avatars/avatar-15.svg",
    alt: "A translucent mechanical device emerging whole from a 3D printer",
  },
  {
    id: "fx33BRAIN33",
    title: "Brain Interfaces Without the Science Fiction",
    channel: "Domestic Futures",
    views: 759_113,
    published: "January 23, 2026",
    duration: "17:42",
    thumbnail: "thumbnails/thumb-33.svg",
    avatar: "avatars/avatar-18.svg",
    alt: "A subtle wearable headband visualizing gentle neural signals",
  },
  {
    id: "fx34CRAFT34",
    title: "Why Handmade Tech Is Growing Again",
    channel: "Tactile Lab",
    views: 184_092,
    published: "April 20, 2026",
    duration: "9:40",
    thumbnail: "thumbnails/thumb-34.svg",
    avatar: "avatars/avatar-16.svg",
    alt: "Hands soldering a beautiful handmade circuit board on a wood workbench",
  },
  {
    id: "fx35LOCAL35",
    title: "The Cloud Is Moving Back Into Your House",
    channel: "Quiet Systems",
    views: 624_803,
    published: "June 1, 2026",
    duration: "14:11",
    thumbnail: "thumbnails/thumb-35.svg",
    avatar: "avatars/avatar-11.svg",
    alt: "A compact home server glowing softly on a shelf beside books",
  },
  {
    id: "fx36ONEAPP6",
    title: "One Interface to Control Everything",
    channel: "Build Relay",
    views: 1_745_380,
    published: "May 26, 2026",
    duration: "10:36",
    thumbnail: "thumbnails/thumb-36.svg",
    avatar: "avatars/avatar-13.svg",
    alt: "Many colorful application windows converging into one calm interface",
  },
] satisfies Array<Omit<Video, "url">>;

export const videos = entries.map((video) => ({
  ...video,
  url: `https://www.youtube.com/watch?v=${video.id}`,
})) satisfies Video[];
